---
title: "2015 CHIS dataset"
author: "Miguel Fudolig, Luke Cho, Lawrence Kim, Boya Liu"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
---


```{r}
library(tidyverse)
```


# Data Set

The data is obtained from the one-year PUF of the 2015 CHIS questionnaire.

```{r}
read_csv("G:/My Drive/UNLV/Research/Asian Adults/CSV CHIS/2015.csv") -> chis_2015
```

```{r}
chis_2015 |> 
  select(c(starts_with("SR"),AH3_P1,USUAL5TP,USOC,AH37,INS)) |> 
  mutate(across(c(SRAA,SRAI:INS),as.factor))->chis_source
```

# Insurance

## Random Forest

```{r}
ins_rf <- chis_source |> select(-c(USOC,USUAL5TP,AH3_P1,SRJP,SRASO2))

set.seed(222)
ind <- sample(2, nrow(ins_rf), replace = TRUE, prob = c(0.7, 0.3))

train <- ins_rf[ind==1,]
test <- ins_rf[ind==2,]

randomForest::randomForest(INS~.,data=train,importance=T)-> rf_wo

pred_noeth <- predict(rf_wo,train,type="response")
caret::confusionMatrix(pred_noeth,train$INS,positive="1")
```

```{r}
pred_noeth <- predict(rf_wo,test,type="response")
caret::confusionMatrix(pred_noeth,test$INS,positive="1")
```


